int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int find_root(int n, int root);
int is_prime_number(int n);
int is_palindrome(char *s);
int helper_palindrome (char *s, int len, int i);
int wildcmp(char *s1, char *s2);
int _compare(char *s1, char *s2, int i1, int i2, int star_present);
int check_s2(char *s2, int i);
